[font]
size = 10.5

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"


[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "F12"
mods = "Control"
